### ISSUE TITLE
Detox tests timing out after setting up Performance Monitoring

### ISSUE THREAD

**Issue by kevindsky** [getsentry/sentry-react-native#1921]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
`"@sentry/react-native": "^3.1.1"`

### Steps to Reproduce

1. Following [instructions](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/) for Performance Monitoring
2. Run tests on debug/release

App
```typescript
function App() {
  return (
    <Provider store={store}>
      <ProviderApp />
    </Provider>
  );
}

export default wrap(App);
```

Config
```
export const ReactNavigationInstrumentation = new Sentry.ReactNavigationInstrumentation({
  routeChangeTimeoutMs: 20000,
});

if (!disableSentry) {
  Sentry.init({
    dsn: process.env.SENTRY_DSN,
    environment: process.env.ENV,
    enableNative: process.env.JEST || disableSentry ? false : true,

    autoSessionTracking: true,
    enableAutoSessionTracking: true,
    sessionTrackingIntervalMillis: 10000,
    integrations: [
      new Sentry.ReactNativeTracing({
        idleTimeout: 5000,
        routingInstrumentation: ReactNavigationInstrumentation,
        tracingOrigins: ['localhost', /^\//, /^https:\/\//],
      }),
    ],
    tracesSampleRate: 0.2, // maybe set this to 100% if __DEV__
  });
}
```

### Expected Result

Tests should pass.

### Actual Result

```
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] WARN:  [PENDING_REQUESTS] The app has not responded to the network requests below:
  (id = 80) invoke: {"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxAssertion"},"method":"assertMatcher","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"androidx.test.espresso.Espresso"},"method":"onView","args":[{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForTestId","args":["email-signin-input"]}}]}},{"type":"Invocation","value":{"target":{"type":"Class","value":"com.wix.detox.espresso.DetoxMatcher"},"method":"matcherForSufficientlyVisible","args":[]}}]}

That might be the reason why the test "My Apps Tests Test using common interface" has timed out.

detox[36483] INFO:  My Apps Tests: Test using common interface [FAIL]

detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
detox[36483] ERROR: [Client.js/ERROR] The pending request #-49642 ("cleanup") has been rejected due to the following error:

The tester has not received a response within 5000ms timeout to the message:

Cleanup {
  type: 'cleanup',
  params: [Object],
  messageId: -49642
}
 FAIL  __tests__/e2e/tests/NavBarTest.tv.e2e.ts (400.848 s)
```

Tests work if the config is commented out

**Comment by marandaneto** [comment]
@kevindsky thanks for reporting, but not sure if this is related to Sentry, it could be that your tests are not considering the performance monitoring or something, the logs don't tell anything related to Sentry either.
Not sure how I can help, does the SDK init normally? does the App init normally? if So, the problem is with your test.

**Comment by kevindsky** [comment]
@marandaneto thanks - without these config they're working fine even with wrapping the root component.

```
    autoSessionTracking: true,
    enableAutoSessionTracking: true,
    sessionTrackingIntervalMillis: 10000,
    integrations: [
      new Sentry.ReactNativeTracing({
        idleTimeout: 5000,
        routingInstrumentation: ReactNavigationInstrumentation,
        tracingOrigins: ['localhost', /^\//, /^https:\/\//],
      }),
    ],
    tracesSampleRate: 0.2, // maybe set this to 100% if __DEV__
  });
```

My gut feeling me there's a long running timer setup in the background?

```
detox[36483] INFO:  [APP_STATUS] App synchronization debug: 
The app is busy, due to: 
         - Enqueued timers
```

I've increased our timeout to 4 minutes and they still fail.

**Comment by marandaneto** [comment]
@jennmueng are you aware of such timers?

**Comment by kevindsky** [comment]
Let me know if I can provide more info @jennmueng @marandaneto

**Comment by marandaneto** [comment]
@kevindsky yes please, provide a minimal reproducible example, it can be an empty/fresh project with one single screen, that enables sentry with performance and Detox tests fail, on GH would be great, thanks.

**Comment by kevindsky** [comment]
@marandaneto setting one up now - will edit this comment once up.

**Comment by shzhng** [comment]
we are also experiencing this. @kevindsky is the temporary fix just to disable sentry init?

**Comment by denissb** [comment]
I had the same issue. This is because performance tracing sets up a timer mechanism to measure the users behaviour.

What helped me was to conditionally disable the tracing integration on JS side like this:
```
Sentry.init({
    dsn: ***,
    tracesSampleRate: 0.2,
    environment: __DEV__ ? 'dev' : 'prod',
    enableAutoSessionTracking: true,
    enableNative: process.env.JEST_WORKER_ID ? false : true,
    integrations: config.isTest
      ? undefined
      : [
          new Sentry.ReactNativeTracing({
            idleTimeout: 5000,
            routingInstrumentation,
            tracingOrigins: ['localhost', /^\//, /^https:\/\//],
        ],
  });
```

I think this is the right solution as you typically would not want tracing on your e2e tests.

**Comment by marandaneto** [comment]
> @marandaneto setting one up now - will edit this comment once up.

any news here?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by papa-jake** [comment]
@marandaneto This is still happening. I just spent a couple days tracking down what was causing our Detox tests to hang. After removing react native tracing instrumentation, our tests now pass successfully. I was able to track down that the timers are being set in the stall tracking: https://github.com/getsentry/sentry-react-native/blob/main/src/js/tracing/stalltracking.ts

I'd be happy to work on a PR with a bit of assistance. For now my solution is detect when it is an e2e test run and not include tracing instrumentation in my integrations.

**Comment by jkadamczyk** [comment]
Hey @marandaneto how's it going?

I noticed that we have the same problem with Sentry Performance still.
Our app is open source so you should be able to easily see the config we have here https://github.com/rainbow-me/rainbow/blob/5c8b168d4af9d1a75c3761455593d250e3d98946/src/App.js#L110

I tracked down the issue with E2E tests and it seems like React Navigation instrumentation is the problem here. If you think it works great and has no problems, that's okay. One thing I would love to see is at least a disclaimer about the problems that can appear when using this integration along with detox e2e tests.
For me I will be disabling this integration when tests are run, would be great to suggest that as a quick-fix until a better solution is found.

**Comment by scarlac** [comment]
I solved this by disabling stall tracking. You can do so conditionally if you only run tests locally:
```js
Sentry.init({
  // ...
  integrations:       [
    new Sentry.ReactNativeTracing({
      // ...
      // Disable stall tracking while testing
      // https://github.com/wix/Detox/blob/master/docs/Troubleshooting.Synchronization.md#settimeout-and-setinterval
      // (Sentry will call setTimeout(checkIfStalled, 0) causing Detox to wait forever
      enableStallTracking:        !__DEV__,
    }),
  ],
  debug: __DEV__,
});
```

**Comment by marandaneto** [comment]
Sorry delay, What if we document that on the https://docs.sentry.io/platforms/react-native/troubleshooting/ page? Telling you to disable those integrations during tests.

I don't think we can do much in the SDK itself, the implementation relies on those timers, and we can't detect automatically if you are running a test or not.

**Comment by jkadamczyk** [comment]
I think documenting is good enough
