### ISSUE TITLE
EXC_BAD_ACCESS RCTModalHostViewController New Issue Unhandled addObject: > numberWithInteger: > Attempted to dereference garbage pointer 0x2bd270000000010

### ISSUE THREAD

**Issue by mouricef** [getsentry/sentry-react-native#1964]
### Environment

**OS - Mac OS**

**Platform:**
iOS

How do you use Sentry?
 Sentry SaaS (sentry.io)

Which SDK and version?
Sentry React Native - 3.2.8

react-native version: 0.64.2

I am using sentry.io, please post a link to your issue so we can take a look:

[issue link](https://sentry.io/share/issue/a66ea8f41a864f6a8da0e7ea10993660/)

Configuration:

````
Sentry.init({
      dsn: "https://xxxxxxxxx.xxxx.sentry.io/xxxxx",
      //Enable Instrumentation
      integrations: [
        new Sentry.ReactNativeTracing({
          routingInstrumentation: reactNavigationV4Instrumentation,
          tracingOrigins: ['localhost', 'xxxxx.xxx.xxx', /^\//, /^https:\/\//],
        }),
      ],
      tracesSampleRate: 1,
      environment: isEmulator ? `${Config.SENTRY_ENV}_simulator` : Config.SENTRY_ENV,
    });
````

### Steps to Reproduce

Previously we were using v2.6.2 and after upgrading to @sentry/react-native v3.2.3, we are experiencing a hard application crash when launching our application with the above Sentry.init 

I tried all the version from 3.2.3 to 3.2.8 but issue is still happening. After downgrading to 2.6.2 I am not observing this issue.Because of this I am not able to upgrade to 3.x 

issue is only happening on iOS (easily reproducible on iOS 12.5.5 )and its not consistent.  If I launch the application 4 to 5 times then one of the launch is crashing. We are observing this issue on iOS 12 and iOS 14

### Expected Result
Application runs as normal

### Actual Result
Application closes immediately upon load of the compiled JS bundle. I have shared the issue link

**Comment by marandaneto** [comment]
@mouricef thanks for reporting.
can you provide a minimal reproducible example? could it be caching issues? have you tried to clean node modules etc?

**Comment by mouricef** [comment]
@marandaneto Yes I tried clean node modules and pods but no luck.

**Comment by marandaneto** [comment]
> provide a minimal reproducible example

ok, so please provide a minimal reproducible example

**Comment by marandaneto** [comment]
@mouricef any news here? thanks

**Comment by mouricef** [comment]
@marandaneto  Give me weeks time. I will provide the minimal reproducible example repo.

**Comment by santiseijas** [comment]
guys any update here? we are getting this error also 
![image](https://user-images.githubusercontent.com/49232269/147455385-5dcebbfc-0764-49f8-a938-81034c22c10b.png)
Thanks!!

**Comment by mouricef** [comment]
@marandaneto 

Sorry for the late reply, I was on vacation the past 10 days

We have a large codebase with lot of dependencies. 

I am working on minimal reproducible example repo and I do have few observations while working on the example repo I will share the details with example repo in a day or two.

**Comment by mouricef** [comment]
@marandaneto 

I am not sure if providing a minimal reproducible example will help or not. Reason I am saying this because while working on the minimal reproducible example I observed that frequency of issue gets reduce with minimum JS code. Frequency of issue with sample repo is 1 crash out of 70 to 80 app launch approx. 

My Observations

- Frequency of issue with our app code base is 1 crash out of 5 app launch approx.
- Frequency of issue with sample repo is 1 crash out of 70 to 80 app launch approx.
- If we set enableSwizzling:false then application work as expected without any Crash.
- Crash is observed mostly on iOS 12.5.5 and iOS 14. Frequency is more on  iOS 12.5.5

Note: Sample repo contains sentry init code and react navigation v4 with App.JS and one component as initial route. 

Let me know if you need the sample repo. Only issue with that repo is you need to launch the application several (launch - kill -launch - kill.......) time and at one of the instance application will crash with above error.

Please find below screenshot from firebase crashlytics, 

<img width="1269" alt="Screenshot 2022-01-04 at 6 41 19 PM" src="https://user-images.githubusercontent.com/90189252/148064506-c0895291-1d3c-4b5a-bc11-ade3a3562713.png">

**Comment by marandaneto** [comment]
@philipphofmann or @brustolin mind checking this stack trace?
this RN version uses Sentry Cocoa 7.5.4

**Comment by philipphofmann** [comment]
It could be that this is fixed with `7.7.0`, which is available in https://github.com/getsentry/sentry-react-native/releases/tag/3.2.9. @mouricef, can you update and let us now, if you still experience the issue.

**Comment by mouricef** [comment]
@philipphofmann , Let me check with the latest version. 

Thanks

**Comment by mouricef** [comment]
@philipphofmann 

we upgraded sentry-react-native to v3.2.11 and unfortunately we still have the same issue.

<img width="1329" alt="Screenshot 2022-01-17 at 6 25 20 PM" src="https://user-images.githubusercontent.com/90189252/149773047-008c2498-1503-41da-a906-0f3ba0c4f2a8.png">

**Comment by philipphofmann** [comment]
Thanks for the update, @mouricef. This could be related to https://github.com/getsentry/sentry-cocoa/issues/1634. We plan to ship a fix soon.

You mentioned 

> Currently Sentry init call is inside the constructor of App component if I move that to componentDidMount and inside the InteractionManager.runAfterInteractions(() => { } ) then no crash is observed. But I am not sure this is correct place to init the sentry. Please confirm.

This is a hint for me, that our logic in SentrySubClassFinder might crash if you dynamically load libraries while it is trying to find subclasses. https://github.com/getsentry/sentry-cocoa/pull/1635 is a potential fix.

**Comment by mouricef** [comment]
Thanks for the update, @philipphofmann.

**Comment by philipphofmann** [comment]
@marandaneto, we just released https://github.com/getsentry/sentry-cocoa/pull/1635 with 7.9.0. Could we bump Cocoa in RN and also do a release?

**Comment by mouricef** [comment]
@marandaneto 

Unfortunately its still crashing.....

Sentry crash log - https://sentry.io/share/issue/a66ea8f41a864f6a8da0e7ea10993660/

**Comment by philipphofmann** [comment]
@mouricef is this still an issue?

**Comment by mouricef** [comment]
@philipphofmann  Unfortunately Yes. It's still crashing.

**Comment by mouricef** [comment]
Thanks @philipphofmann

**Comment by philipphofmann** [comment]
@marandaneto, can we bump sentry-cocoa to [7.10.2](https://github.com/getsentry/sentry-cocoa/releases/tag/7.10.2) and see if it fixes this problem as we released https://github.com/getsentry/sentry-cocoa/pull/1692 with it.
