### ISSUE TITLE
RNSentry.captureEnvelope got 3 arguments, expected 4

### ISSUE THREAD

**Issue by pdavid0** [getsentry/sentry-react-native#2505]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.5.0

**`react-native` version:** 0.69.4

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

https://sentry.io/organizations/inspectify/issues/3629448282/?project=5740339&query=is%3Aunresolved&statsPeriod=1h

**Configuration:**

```
const routingInstrumentation = new Sentry.Native.ReactNavigationInstrumentation();
Sentry.init({
  dsn: SENTRY_DSN,
  enableInExpoDevelopment: SENTRY_ENABLE_IN_DEV,
  debug: SENTRY_DEBUG,
  environment: process.env.NODE_ENV,
  tracesSampleRate: 0.2,
  integrations: [
    new Sentry.Native.ReactNativeTracing({
      routingInstrumentation,
    }),
  ],
});

```

---
**I have following issue:**

Upgrading to version `5.0.0-alpha.4` or `4.5.0` makes the app crash

**Steps to reproduce:**
- Install Sentry
- Make the App Crash

**Actual result:**

```
FATAL EXCEPTION: mqt_native_modules
Process: com.company.myapp, PID: 13737
com.facebook.react.bridge.NativeArgumentsParseException: RNSentry.captureEnvelope got 3 arguments, expected 4
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:223)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:923)
```

**Expected result:**

- Sentry does not crash

**Comment by krystofwoldrich** [comment]
Hi, we made a change in our native layer and this error happens, when the native layer is not rebuild after the upgrade.

Clean build should solve this. Let me know if it helped.

**Comment by pdavid0** [comment]
@krystofwoldrich thanks, it seems to work in debug mode, but the error first came through a CI build, which should be clean by default.

**Comment by pdavid0** [comment]
Spoke too soon, a clean build with version `5.0.0-alpha.4` still crashes in debug.

**Comment by pdavid0** [comment]
downgrading to `alpha.3` and cleaning the build works.

```bash
cd android && ./gradlew clean && cd ..
yarn react-native run-android
```

**Comment by krystofwoldrich** [comment]
I have suspicion that when you upgrade the native java code doesn't get recompiled. That would explained why downgrading to `alpha.3` works, because it uses the older native code.

**Comment by krystofwoldrich** [comment]
If the problem persist could you share a repo or send sample which doesn't build, so I can try to reproduce it?

**Comment by pdavid0** [comment]
> If the problem persist could you share a repo or send sample which doesn't build, so I can try to reproduce it?
Will do if I can't make it work by tomorrow .. it will probably have to wait until Monday.

I've looked at the code it downloads locally for `alpha.4`

```java
// build.gradle
dependencies {
    implementation 'com.facebook.react:react-native:+'
    api 'io.sentry:sentry-android:6.4.2'
}
```

```java
    // RNSentryModule.java
    @ReactMethod
    public void captureEnvelope(ReadableArray rawBytes, ReadableMap options, Promise promise) {
```

So im not sure where's the issue

**Comment by marandaneto** [comment]
@pdavid0 likely a cache issue, clean `node_modules` and clean caches, we have tests running on CI so I don't think this is a bug at all.

**Comment by pdavid0** [comment]
Closing as I couldn't reproduce in a clean App ... 

Thanks for the support

**Comment by krystofwoldrich** [comment]
> 4.6.0 have this issue on app launch

Hi, make sure you do a clean build since this is caused by using a cached native layer build from previous versions.

**Comment by CursedMun** [comment]
> > 4.6.0 have this issue on app launch
> 
> Hi, make sure you do a clean build since this is caused by using a cached native layer build from previous versions.

This happened on production build `eas build --profile production --platform android` should I pass an argument to clear it?

**Comment by krystofwoldrich** [comment]
You can try `--clear-cache`, [docs](https://github.com/expo/eas-cli#eas-build), but I personally don't use expo so, I don't know.



I clean the build using Android Studio and Xcode.

**Comment by JeremyBradshaw7** [comment]
I'm having this also. Cleaning doesn't seem to help. Not using expo though.
