### ISSUE TITLE
@sentry/cli with expo fails eas release builds when adding configs to app.json or app.config.ts

### ISSUE THREAD

**Issue by medomy** [getsentry/sentry-react-native#5033]
### What React Native libraries do you use?

React Navigation, Expo Application Services (EAS), Expo (mobile only)

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

6.19.0

### How does your development environment look like?

````
⬇  Place the `npx react-native@latest info` output here. ⬇ 

System:
  OS: macOS 15.3.2
  CPU: (8) arm64 Apple M2
  Memory: 120.91 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.11.0/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.2
      - iOS 18.2
      - macOS 15.2
      - tvOS 18.2
      - visionOS 2.2
      - watchOS 11.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.3 AI-243.26053.27.2432.13536105
  Xcode:
    version: 16.2/16C5032a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 19.1.1
    wanted: latest
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.7
    wanted: 0.76.7
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false


````

### Sentry.init()

````js
Sentry.init({
    dsn: "https://de36581d16fb423c973f3a16b14b42b5@o164516.ingest.us.sentry.io/6042935",
    environment: ENV.EXPO_PUBLIC_CHANNEL,
    dist: `${ENV.EXPO_PUBLIC_CHANNEL}/${AppJson.version}`,
    release: `${ENV.EXPO_PUBLIC_CHANNEL}/${AppJson.version}`,
  });
````

### Steps to Reproduce

1. add your config to app.json or app.config.ts as follows  
````ts
export default ({ config: _config }: ConfigContext): CustomExpoConfig => {
  const plugins = _config.plugins ?? [];
  if (process.env.NODE_ENV !== "development") {
    plugins.push([
      "@sentry/react-native/expo",
      {
        url: "https://sentry.io/",
        organization: "organiztion_name",
        project: "project_name"
      },
    ]);
  }

  return {
    ..._config,
    name: config.name,
    slug: config.slug,
    scheme: config.scheme,
    owner: config.owner,
    splash: {
      ..._config.splash,
      backgroundColor: config.splashBackgroundColor,
    },
    updates:
      process.env.NODE_ENV === "development"
        ? undefined
        : {
            url: `https://api.expo-updates.oraganization-members.com/api/manifest?project=${config.slug}&channel=${channel}`,
            requestHeaders: {
              "release-channel": channel,
              "expo-release-channel": channel,
            },
            fallbackToCacheTimeout: 10 * 1000,
            codeSigningCertificate: "./certificate.pem"
          },

    ios: {
      ...(_config.ios as Any),
      bundleIdentifier: config.bundleIdentifier,
      entitlements: {
        "aps-environment":
          channel === "development" ? "development" : "production",
      },
      config: {
        usesNonExemptEncryption: false,
      },
    },
    android: {
      adaptiveIcon: {
        foregroundImage: "./assets/adaptive-icon.png",
        backgroundColor: config.adaptiveIconBackgroundColor,
      },
      package: config.bundleIdentifier,
      googleServicesFile: "./google-services.json",
      blockedPermissions: ["com.google.android.gms.permission.AD_ID"],
    },
    plugins: [
      ...plugins,
      [
        "@bacons/link-assets",
        [
          "fonts/Rubik-Bold.ttf",
          "fonts/Rubik-Regular.ttf",
          "fonts/Rubik-SemiBold.ttf",
        ],
      ],
      [
        "app-icon-badge",
        {
          enabled: process.env?.NODE_ENV !== "production",
          badges: [
            {
              text: process.env?.NODE_ENV ?? "development",
              type: "banner",
              color: "#ffffff",
              background: "#34c759",
            },
            {
              text: `${_config.runtimeVersion}`,
              type: "ribbon",
              color: "#ffffff",
              background: "#007aff",
            },
          ],
        },
      ],
    ],
    extra: { eas: { projectId: config.id } },
  };
};
````
2. run command "eas build -p android --profile {your_profile} --local" or "eas build -p ios --profile {your_profile} --local" in terminal
3. wait for build artifacts to be created and notice logs

### Expected Result

For the build artifacts to be successfully created

### Actual Result

1. In case of not adding config everything works fine and build artifacts get bundled
2. in case of adding config I get errors in building iOS without any clear logs and the following error in Android build 
````bash
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUploadCleanUp SKIPPED
[RUN_GRADLEW] 71 actionable tasks: 71 executed
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets_SentryUpload_com.zeal.dashboard@2.9.3+23_23'.
[RUN_GRADLEW] > A problem occurred starting process 'command '/private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/03eb63d6-da57-4391-857b-a39d7bfe7513/build/dashboard-app/node_modules/@sentry/cli/bin/sentry-cli''
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 31s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.
````

**Comment by lucas-zimerman** [comment]
Hi and thank you for opening this issue!
Would you be able to check if your project builds with Sentry React Narive version 6.17.0?

**Comment by medomy** [comment]
Hi @lucas-zimerman and thanks for replying ,, 
I've checked version 6.17.0 and same issue 
Android build logs 
````bash
[RUN_GRADLEW] > Task :app:checkReleaseAarMetadata
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.zeal.dashboard@2.9.3+23_23 FAILED
[RUN_GRADLEW] Copy `debugId` from packager source map to Hermes source map...
[RUN_GRADLEW] Done.
[RUN_GRADLEW] Check generated source map for Debug ID: c65f2051-ab59-466c-9998-7ed707897695
[RUN_GRADLEW] Sentry Source Maps upload will include the release name and dist.
[RUN_GRADLEW] Sentry-CLI arguments: [/private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/node_modules/@sentry/cli/bin/sentry-cli, react-native, gradle, --bundle, /private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle, --sourcemap, /private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map, --release, com.zeal.dashboard@2.9.3+23, --dist, 23]
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUploadCleanUp SKIPPED
[RUN_GRADLEW] 71 actionable tasks: 71 executed
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets_SentryUpload_com.zeal.dashboard@2.9.3+23_23'.
[RUN_GRADLEW] > A problem occurred starting process 'command '/private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/node_modules/@sentry/cli/bin/sentry-cli''
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 36s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.
````

**Comment by Marcin-Falkowski** [comment]
Similar problem with flavours i think. I have flavoring configuration - a few apps to one sentry project. Nothing changed -> yesterday it worked properly -> today errors due to uploading source maps:

error: API request failed

Caused by:
    sentry reported an error: You do not have permission to perform this action. (http status: 403)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

Sentry skipping default config and creating source with name non compliant to the sentry project.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/vagrant/git/node_modules/@sentry/react-native/sentry.gradle' line: 149

* What went wrong:
Execution failed for task ':app:createBundleBigDataReleaseJsAndAssets_SentryUpload_com.badName@5.4.3+99_99'.
> Process 'command '/Users/vagrant/git/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1



    "@sentry/react-native": "6.17.0",

**Comment by lucas-zimerman** [comment]
> Hi [@lucas-zimerman](https://github.com/lucas-zimerman) and thanks for replying ,, I've checked version 6.17.0 and same issue Android build logs
> 
> [RUN_GRADLEW] > Task :app:checkReleaseAarMetadata
> [RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.zeal.dashboard@2.9.3+23_23 FAILED
> [RUN_GRADLEW] Copy `debugId` from packager source map to Hermes source map...
> [RUN_GRADLEW] Done.
> [RUN_GRADLEW] Check generated source map for Debug ID: c65f2051-ab59-466c-9998-7ed707897695
> [RUN_GRADLEW] Sentry Source Maps upload will include the release name and dist.
> [RUN_GRADLEW] Sentry-CLI arguments: [/private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/node_modules/@sentry/cli/bin/sentry-cli, react-native, gradle, --bundle, /private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle, --sourcemap, /private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map, --release, com.zeal.dashboard@2.9.3+23, --dist, 23]
> [RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUploadCleanUp SKIPPED
> [RUN_GRADLEW] 71 actionable tasks: 71 executed
> [RUN_GRADLEW] FAILURE: Build failed with an exception.
> [RUN_GRADLEW] * What went wrong:
> [RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets_SentryUpload_com.zeal.dashboard@2.9.3+23_23'.
> [RUN_GRADLEW] > A problem occurred starting process 'command '/private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/node_modules/@sentry/cli/bin/sentry-cli''
> [RUN_GRADLEW] * Try:
> [RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
> [RUN_GRADLEW] > Run with --info or --debug option to get more log output.
> [RUN_GRADLEW] > Run with --scan to get full insights.
> [RUN_GRADLEW] > Get more help at https://help.gradle.org.
> [RUN_GRADLEW] BUILD FAILED in 36s
> [RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> 
> Build failed
> Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> npx exited with non-zero code: 1
>     Error: build command failed.

Thank you for your return! It seems like unrelated to a recent SDK issue then.

Would you be able to build using the following command? `SENTRY_LOG_LEVEL=debug && eas build -p android --profile production --local`
This way the SDK will give more explanation on the issue

**Comment by medomy** [comment]
> > Hi [@lucas-zimerman](https://github.com/lucas-zimerman) and thanks for replying ,, I've checked version 6.17.0 and same issue Android build logs
> > [RUN_GRADLEW] > Task :app:checkReleaseAarMetadata
> > [RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.zeal.dashboard@2.9.3+23_23 FAILED
> > [RUN_GRADLEW] Copy `debugId` from packager source map to Hermes source map...
> > [RUN_GRADLEW] Done.
> > [RUN_GRADLEW] Check generated source map for Debug ID: c65f2051-ab59-466c-9998-7ed707897695
> > [RUN_GRADLEW] Sentry Source Maps upload will include the release name and dist.
> > [RUN_GRADLEW] Sentry-CLI arguments: [/private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/node_modules/@sentry/cli/bin/sentry-cli, react-native, gradle, --bundle, /private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle, --sourcemap, /private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map, --release, com.zeal.dashboard@2.9.3+23, --dist, 23]
> > [RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUploadCleanUp SKIPPED
> > [RUN_GRADLEW] 71 actionable tasks: 71 executed
> > [RUN_GRADLEW] FAILURE: Build failed with an exception.
> > [RUN_GRADLEW] * What went wrong:
> > [RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets_SentryUpload_com.zeal.dashboard@2.9.3+23_23'.
> > [RUN_GRADLEW] > A problem occurred starting process 'command '/private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/5fec66ec-0772-46a6-8758-47e101160668/build/dashboard-app/node_modules/@sentry/cli/bin/sentry-cli''
> > [RUN_GRADLEW] * Try:
> > [RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
> > [RUN_GRADLEW] > Run with --info or --debug option to get more log output.
> > [RUN_GRADLEW] > Run with --scan to get full insights.
> > [RUN_GRADLEW] > Get more help at https://help.gradle.org.
> > [RUN_GRADLEW] BUILD FAILED in 36s
> > [RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> > Build failed
> > Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
> > npx exited with non-zero code: 1
> > Error: build command failed.
> 
> Thank you for your return! It seems like unrelated to a recent SDK issue then.
> 
> Would you be able to build using the following command? `SENTRY_LOG_LEVEL=debug && eas build -p android --profile production --local` This way the SDK will give more explanation on the issue

I have tried building with `SENTRY_LOG_LEVEL=debug && eas build -p android --profile production --local` and got same logs I guess , no extra information 
````bash
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.zeal.dashboard@2.9.3+24_24 FAILED
[RUN_GRADLEW] Copy `debugId` from packager source map to Hermes source map...
[RUN_GRADLEW] Done.
[RUN_GRADLEW] Check generated source map for Debug ID: 757793e7-ee03-4e9c-8a0a-e1c1272ead7e
[RUN_GRADLEW] Sentry Source Maps upload will include the release name and dist.
[RUN_GRADLEW] Sentry-CLI arguments: [/private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/cf2ecedd-253c-4194-b0f8-61ca8af3b396/build/dashboard-app/node_modules/@sentry/cli/bin/sentry-cli, react-native, gradle, --bundle, /private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/cf2ecedd-253c-4194-b0f8-61ca8af3b396/build/dashboard-app/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle, --sourcemap, /private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/cf2ecedd-253c-4194-b0f8-61ca8af3b396/build/dashboard-app/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map, --release, com.zeal.dashboard@2.9.3+24, --dist, 24]
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets_SentryUploadCleanUp SKIPPED
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets_SentryUpload_com.zeal.dashboard@2.9.3+24_24'.
[RUN_GRADLEW] > A problem occurred starting process 'command '/private/var/folders/vs/cstvs9vj6p7f8yf3ycqqc4480000gn/T/eas-build-local-nodejs/cf2ecedd-253c-4194-b0f8-61ca8af3b396/build/dashboard-app/node_modules/@sentry/cli/bin/sentry-cli''
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan
[RUN_GRADLEW] 25 actionable tasks: 25 executed
[RUN_GRADLEW] to get full insights.
[RUN_GRADLEW] > Get more help at https://help.gradle.org.
[RUN_GRADLEW] BUILD FAILED in 32s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.
````

**Comment by medomy** [comment]
I'd like to add more context to this as it might be helpful ,, this is a mono-repo that I'd done recently ,, before there were seperate repos using yarn and version 6.3.0 of the library and everything was fine ,, now I'm using pnpm with the versions we mentioned 6.19.0 and 6.17.0 we tried and also 6.3.0 we tried before all of them ,, I don't know if that's helpful or not

**Comment by lucas-zimerman** [comment]
Thank you for the additional information and yes pnpm might be the reason why things are not working as expected.

would you be able to run the following command on the folder that you invoke the eas build command?
`cat "$(pnpm root)/@sentry/react-native/node_modules/.bin/sentry-cli"`

This should print the folder that pnpm linked to sentry/cli

If it prints anything, would you be able to check if the first export file points to a folder that exists on your node module? the path should be similar to this:

```
  export NODE_PATH="/run/media/lucas/.../packages/app/node_modules/.pnpm/@sentry+cli@2.50.2/node_modules/@sentry/cli/bin/node_modules:..."
```

Also for the time being, one mitigation you could try on your end is to manually add @sentry/cli to your package.json, this should enforce pnpm to add it to the usual node_modules path

**Comment by medomy** [comment]
@lucas-zimerman ,, so sorry for the late response , I've checked the folder and it points to the node_modules on the mono-repo level but not to the node_modules in the app level itself ,, can this be the issue ? 

for adding @sentry/cli to my package.json it seems to have solved the issue temporarily

**Comment by Haider-Ali-7** [comment]
I'm facing similar issue.

-  Where:
[RUN_GRADLEW] Script '/private/var/folders/6r/69pk744j6zn5gzgym4_nm5z80000gp/T/eas-build-local-nodejs/36733a7a-8d52-4e65-a8e2-431f8924956c/build/node_modules/@sentry/react-native/sentry.gradle' line: 149
- What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets_SentryUpload_com.rishtaaunty@1.0.0+1_1'.

> Process 'command '/private/var/folders/6r/69pk744j6zn5gzgym4_nm5z80000gp/T/eas-build-local-nodejs/36733a7a-8d52-4e65-a8e2-431f8924956c/build/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1

```
"expo": "^53.0.20",
"@sentry/react-native": "^7.0.1"
```

**Comment by lucas-zimerman** [comment]
> I'm facing similar issue.
> 
>     * Where:
>       [RUN_GRADLEW] Script '/private/var/folders/6r/69pk744j6zn5gzgym4_nm5z80000gp/T/eas-build-local-nodejs/36733a7a-8d52-4e65-a8e2-431f8924956c/build/node_modules/@sentry/react-native/sentry.gradle' line: 149
> 
>     * What went wrong:
>       [RUN_GRADLEW] Execution failed for task ':app:createBundleReleaseJsAndAssets_SentryUpload_com.rishtaaunty@1.0.0+1_1'.
> 
> 
> > Process 'command '/private/var/folders/6r/69pk744j6zn5gzgym4_nm5z80000gp/T/eas-build-local-nodejs/36733a7a-8d52-4e65-a8e2-431f8924956c/build/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1
> 
> ```
> "expo": "^53.0.20",
> "@sentry/react-native": "^7.0.1"
> ```

Would you be able to share your build logs with the following command?
```
export SENTRY_LOG_LEVEL=debug && yarn android-release
```
Whereas `yarn android-release` is the command you use for generating the local release.

**Comment by Haider-Ali-7** [comment]
@lucas-zimerman Thanks for reply. But issue got resolved after I added `uploadSourceMap` attribute in `app.json` file and I'm able to build eas preview build locally.

```
  [
        "@sentry/react-native/expo",
        {
          "url": "https://sentry.io/",
          "project": "your-project-name",
          "organization": "your-organization",
          "uploadSourceMaps": true  // this attribute
        }
     ]
```

**Comment by lucas-zimerman** [comment]
That is an interesting find!
does it break if you set `uploadSourceMaps` as `false` or simply remove it?

**Comment by Haider-Ali-7** [comment]
So I checked it again and it only breaks If I remove it.

**Comment by stefanosiano** [comment]
@Haider-Ali-7 thanks for confirming!
@lucas-zimerman what do you think?

**Comment by lucas-zimerman** [comment]
I wasn't able to reproduce it, would you be able to make a minimal app that produces this issue and share with us? This will help us to speed up the investigation of this issue! 🙇

**Comment by ilyagru** [comment]
The problem has been resolved when I added `@sentry/cli` in devDeps.

**Comment by blue86321** [comment]
> The problem has been resolved when I added `@sentry/cli` in devDeps.

Same issue. can confirm it's because of `@sentry/cli` not in devDeps. After adding it, sentry just works.

Still don't know the root cause, since `eas build --local` works as normal on my laptop.
But on Expo server just fails if no `@sentry/cli` in devDeps.

It took me 2 days and did lots of trial and error.

**Comment by jgarplind** [comment]
I ran into the same issue when trying to replace our pnpm `hoisted` monorepo setup with the since Expo 54 supported `isolated` (default) setup (see https://docs.expo.dev/guides/monorepos/#package-managers-with-isolated-dependencies).

Adding `@sentry/cli` was a missing piece which I didn't think to add until visiting this thread.

Would be great to have it acknowledged, explained or something else that makes this not-too-far-fetched-use-case (pnpm monorepo with `@sentry/react-native`) a supported workflow, not requiring everyone to find a cancelled Github issue to get things running.. :)

---

Unfortunately, I can't easily share a full reproducible setup at this time, but the main building blocks that put me in a situation where the app wouldn't build were:
- Expo 54
- @sentry/react-native 7.2.0
- pnpm monorepo set up as per https://docs.expo.dev/guides/monorepos
- Building for Android in EAS, using pnpm@10.9.0 (default installation in EAS)

**Comment by manutheblacker** [comment]
It would be great to have this added to the official documentation.
