### ISSUE TITLE
using withSentry prevent sourcemap upload for expo update to work

### ISSUE THREAD

**Issue by wcastand** [getsentry/sentry-react-native#5303]
### What React Native libraries do you use?

Expo Application Services (EAS)

### Are you using sentry.io or on-premise?

sentry.io (SaS)

### @sentry/react-native SDK Version

~7.2.0

### How does your development environment look like?

it's `npx expo-env-info`

````
 expo-env-info 2.0.7 environment info:
    System:
      OS: macOS 26.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.16.0 - ~/.nvm/versions/node/v22.16.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v22.16.0/bin/yarn
      npm: 10.9.2 - ~/.nvm/versions/node/v22.16.0/bin/npm
      Watchman: 2025.09.15.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 25.0, iOS 26.0, macOS 26.0, tvOS 26.0, visionOS 26.0, watchOS 26.0
    IDEs:
      Android Studio: 2025.1 AI-251.26094.121.2513.14007798
      Xcode: 26.0.1/17A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: 54.0.19 => 54.0.19
      expo-router: ~6.0.13 => 6.0.13
      expo-updates: ~29.0.12 => 29.0.12
      react: 19.1.0 => 19.1.0
      react-dom: 19.1.0 => 19.1.0
      react-native: 0.81.5 => 0.81.5
    npmGlobalPackages:
      eas-cli: 16.24.1
    Expo Workflow: bare


````

### Sentry.init()

````js
Sentry.init({

	attachViewHierarchy: false,
	defaultIntegrations: false,
	dsn: "my stuff",
	enableAppHangTracking: true,
	enableLogs: true,
	enableNativeFramesTracking: !isRunningInExpoGo(),
	environment: Env.IS_DEV ? "development" : "production",
	integrations: [
		Sentry.functionToStringIntegration,
		Sentry.nativeLinkedErrorsIntegration,
		Sentry.httpContextIntegration,
		Sentry.dedupeIntegration(),
		Sentry.reactNativeErrorHandlersIntegration(),
		Sentry.hermesProfilingIntegration(),
	],
	profilesSampleRate: Env.IS_DEV ? 1.0 : 0.2,
	sendDefaultPii: true,
	tracesSampleRate: Env.IS_DEV ? 1.0 : 0.2,
});
````

### Steps to Reproduce

- setup like the doc says for app.config.ts with `withSentry`
- try to upload sourcemaps after an update

### Expected Result

upload the sourcemaps for the expo update

### Actual Result

getting this error on eas workflow:

```
env: load .env.local
🐕 Fetching from expo config...
Could not fetch '@sentry/react-native' plugin properties from expo config.
/bin/bash -eo pipefail /tmp/eas-build/7ebd48dc-4b67-4376-b611-112b90fce012/steps/d767ba07-51c1-4f35-b9c6-83ed0faa32bb/scripts/d4f6fed2-b252-4d0c-a8cb-d4379e0c8d93.sh exited with non-zero code: 1
```

**Comment by wcastand** [comment]
using the example of `app.json` where i put the plugin in `plugins` seems to work.
but was trying the other way thinking it could be the reason sourcemaps seems to not link properly but after looking it seems to not be related since it does the exact same thing.

**Comment by antonis** [comment]
Thank you for reporting and iterating on this @wcastand 🙇 

> using the example of `app.json` where i put the plugin in `plugins` seems to work.

My understanding is that the issue is solved. Let us know if this is not the case and we will be happy to investigate this further 🙏 

Linking the [related doc](https://docs.sentry.io/platforms/react-native/sourcemaps/uploading/expo/) for future reference.

**Comment by janek515** [comment]
The issue is still present the `withSentry` function is incompatible with the sourcemap upload script, you need to put the plugin manually in the plugins array (as if you were using `app.json`), but this isn't noted anywhere in the documentation.
