### ISSUE TITLE
@sentry/react-native - Hermes Support

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-react-native#649]
The current version as of `1.0.1` we have very basic support for Hermes bundles meaning we are able to get function names but not showing the correct line number / source code for the crash.

In order for us to support it fully, we need to do some changes on how we process minified sources and source maps on the server.

Keep an eye on this issue if you are interested in this topic.

### 1.0.1
![image](https://user-images.githubusercontent.com/363802/64152975-0d643800-ce2e-11e9-8f5b-852181b5a7e7.png)

**Comment by motiz88** [comment]
@HazAT: Please let me know if there's anything we can do on React Native side to make this easier.

**Comment by HazAT** [comment]
@motiz88 Thanks again :)

Is there any way to output the minified js bundle that hermes uses internally?
The reason we need the minified code is that we try to get the function name from the crashed line and our symbolication code needs the minified bundle in order to do this correctly.

We initially thought the `x_facebook_source` is used for that but in our examples the value in there is always `null`.

**Comment by motiz88** [comment]
x_facebook_sources is indeed designed for this (and is inherently more robust and complete than inspecting the bundled JS) so let's make it work. Can you share a complete example where it doesn't work for you?

**Comment by HazAT** [comment]
@motiz88 https://github.com/HazAT/testhermes

**Comment by HazAT** [comment]
@motiz88 If you need anything else from me, please let me know.

**Comment by motiz88** [comment]
@HazAT React Native 0.61 updates Metro (transitively via the RN CLI) to a version that populates `x_facebook_sources`. Could you test against that? We did not bump the Metro dependency in RN 0.60 because it had unrelated breaking changes.

**Comment by HazAT** [comment]
@motiz88 there is no `0.61.0` in the RN CLI yet, but will try again

**Comment by HazAT** [comment]
@motiz88 I can confirm with `0.61.0` `x_facebook_sources` is filled, let's see when we find time implementing this :)

**Comment by tobi512** [comment]
Hi @HazAT, any timeline updates yet?
Would be great to see this as fast as possible since Hermes will drastically reduce our APK size and improve overall JS performance, two of our main pain points at the moment...

**Comment by filipef101** [comment]
Will this mean react-native-v8 will be suported?

**Comment by gaykov** [comment]
Hello @HazAT!

Is there anything the community can help with? I think it's kind of a blocking issue for a lot of RN developers as it's impossible to use Sentry with Hermes now.

Could you please let us know how we can help or is there any timeline on fixing it from Sentry's side?

**Comment by HazAT** [comment]
@gaykov Thank you for offering your help 🙏 
Sadly adding this is not trivial, it requires mostly changes in sentry-cli which is written in rust.
Of course we gladly accept PRs but even I can’t tell you right now what exactly needs to be implemented to make this work.
What I can tell you; this is for sure on our roadmap but can’t give you any exact dates but I wouldn’t expect it in the upcoming weeks, realistic is Q1 2020.

**Comment by mitsuhiko** [comment]
So a quick description of the problem from me (who built a lot of the current version of the source map processing) for why Hermes is different:

Under normal circumstances we use the source map and minified file to look up a location in the source map, then reverse tokenize from that location in the minified source to the last function declaration that matches the function name in the backtrace. Then we use the source map to map this back into the original token at that location. This is described in greater detail here: https://blog.sentry.io/2019/07/16/building-sentry-source-maps-and-their-problems

With Hermes this approach no longer works because Hermes doesn't actually have source maps or minified source code. Instead if has something similar to source maps where the column offset is a bytecode instruction. Since there is no minified source, there is nothing to step back on. Additionally it requires changes to how the filenames are processed in the stack traces because there is again no actual minified file that shows up there.

If someone is interested in helping out on the implementation of this I can go into further detail on discord and explain the current ideas I have for dealing with it.

**Comment by HazAT** [comment]
Short update, @Swatinem did an amazing job, we have Hermes internally implemented and tested.
We need to bump dependencies and release everything, we will ship support for Hermes support probably next week including using our new Android SDK, stay tuned. 

https://github.com/getsentry/sentry-react-native/pull/749

Kudos to @bruno-garcia @marandaneto

**Comment by HazAT** [comment]
`1.3.0` has been released with Hermes support!
There aren't any breaking changes, please check and double-check to delete all caches to make sure you have to latest version.

Thank you all for your patience!

**Comment by desmondmc** [comment]
@HazAT thanks for the updates! Maybe i'm doing something wrong but i just updated to 1.3.0 and i'm getting the following error when compiling: Do we need to have a `minSdkVersion>=26` for this update to work?

```
> Transform artifact sentry-android-core.aar (io.sentry:sentry-android-core:2.0.0-rc04) with DexingNoClasspathTransform
AGPBI: {"kind":"error","text":"Invoke-customs are only supported starting with Android O (--min-api 26)","sources":[{}],"tool":"D8"}

> Transform artifact sentry-core.jar (io.sentry:sentry-core:2.0.0-rc04) with DexingNoClasspathTransform
AGPBI: {"kind":"error","text":"Default interface methods are only supported starting with Android N (--min-api 24): void io.sentry.core.IHub.addBreadcrumb(io.sentry.core.Breadcrumb)","sources":[{}],"tool":"D8"}
```

**Comment by mxmzb** [comment]
Looks like I have issues with the dependency `io.sentry:sentry-android:2.0.0-rc04` here after the update. I'll investigate more in-depth tomorrow, meanwhile here is what Android SDK says:

```
org.gradle.api.internal.tasks.TaskDependencyResolveException: Could not determine the dependencies of task ':app:preDebugBuild'.
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:68)
	at org.gradle.execution.plan.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:46)
	at org.gradle.execution.plan.LocalTaskNode.getDependencies(LocalTaskNode.java:106)
	at org.gradle.execution.plan.LocalTaskNode.resolveDependencies(LocalTaskNode.java:79)
	at org.gradle.execution.plan.DefaultExecutionPlan.addEntryTasks(DefaultExecutionPlan.java:175)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.addEntryTasks(DefaultTaskExecutionGraph.java:139)
	at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:48)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:57)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$2.proceed(DefaultBuildConfigurationActionExecuter.java:63)
	at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:57)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$2.proceed(DefaultBuildConfigurationActionExecuter.java:63)
	at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:57)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.run(DefaultBuildConfigurationActionExecuter.java:43)
	at org.gradle.internal.Factories$1.create(Factories.java:25)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry.withLenientState(DefaultProjectStateRegistry.java:132)
	at org.gradle.api.internal.project.DefaultProjectStateRegistry.withLenientState(DefaultProjectStateRegistry.java:124)
	at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:39)
	at org.gradle.initialization.DefaultTaskExecutionPreparer.prepareForTaskExecution(DefaultTaskExecutionPreparer.java:38)
	at org.gradle.initialization.NotifyingTaskExecutionPreparer$CalculateTaskGraph.populateTaskGraph(NotifyingTaskExecutionPreparer.java:82)
	at org.gradle.initialization.NotifyingTaskExecutionPreparer$CalculateTaskGraph.run(NotifyingTaskExecutionPreparer.java:57)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.initialization.NotifyingTaskExecutionPreparer.prepareForTaskExecution(NotifyingTaskExecutionPreparer.java:45)
	at org.gradle.initialization.DefaultGradleLauncher.prepareTaskExecution(DefaultGradleLauncher.java:205)
	at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:141)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:125)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:105)
	at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:58)
	at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:55)
	at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:82)
	at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:75)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:183)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:75)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:55)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:54)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:58)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:49)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:46)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:46)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1195)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2100(DefaultConfiguration.java:138)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationTaskDependency.visitDependencies(DefaultConfiguration.java:1661)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:106)
	at org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:211)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
	at org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
	at org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
	... 113 more
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find io.sentry:sentry-android:2.0.0-rc04.
Searched in the following locations:
  - file:/Users/maxim/.m2/repository/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
  - file:/Users/maxim/.m2/repository/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
  - file:/Volumes/Projects/goodtendency/packages/goodtendency-app/node_modules/react-native/android/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
  - file:/Volumes/Projects/goodtendency/packages/goodtendency-app/node_modules/react-native/android/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
  - file:/Volumes/Projects/goodtendency/packages/goodtendency-app/node_modules/jsc-android/dist/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
  - file:/Volumes/Projects/goodtendency/packages/goodtendency-app/node_modules/jsc-android/dist/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
  - https://dl.google.com/dl/android/maven2/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
  - https://dl.google.com/dl/android/maven2/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
  - https://jcenter.bintray.com/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
  - https://jcenter.bintray.com/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
  - https://jitpack.io/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
  - https://jitpack.io/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
Required by:
    project :app > project :@sentry_react-native
    project :app > project :sentry_react-native
```

**Comment by marandaneto** [comment]
@mxmzb hey, we already have an issue for that, please look at #767 there's a workaround over there, thanks.

**Comment by bruno-garcia** [comment]
@mxmzb we're merged packages on jcenter and that seems to have unlisted our package.
We're working on a fix. Please follow this thread:
https://github.com/getsentry/sentry-android/issues/270

**Comment by marandaneto** [comment]
it should be fixed :)

**Comment by capJavert** [comment]
I am still getting the same gibberish even after upgrading and uploading the new release with updated sourcemaps. Any tips if I am missing something?

Thinks I did:
* updated sentry
* cleared android caches
* updated versionCode
* fresh build + upload to sentry
 
![image](https://user-images.githubusercontent.com/9803078/75090267-6ef59b80-5561-11ea-95bd-6c071d76fef9.png)

**Comment by marandaneto** [comment]
@capJavert hey, it might be related to #772

**Comment by capJavert** [comment]
Not really, My sourcemaps are generated and uploaded and look fine but for some reason when error happens its still like the image above.

**Comment by HazAT** [comment]
@capJavert Can you please link to this issue on sentry.io?

**Comment by capJavert** [comment]
Nope, we use private instance of sentry inside the company. So the screenshot is from there. That is why I asked if some specific version of sentry server is required for this feature.

**Comment by HazAT** [comment]
I am pretty sure we didn't release an official image containing support for Hermes. You need to use the latest master or wait for the new release (I can't tell you when this will be).

**Comment by mxmzb** [comment]
> I am pretty sure we didn't release an official image containing support for Hermes. You need to use the latest master or wait for the new release (I can't tell you when this will be).

But it says so in the release notes: https://github.com/getsentry/sentry-react-native/releases/tag/1.3.0

**Comment by bruno-garcia** [comment]
@HazAT was talking about Sentry. There are lots of changing on the backend to support this.
We've built it and deployed to sentry.io (we deploy multiple times a day to production). If you're running Sentry on-premise, you'll likely using [our Docker files](https://github.com/getsentry/onpremise). Sentry now builds new images for each commit to master:

https://hub.docker.com/r/getsentry/sentry

You will need to update your on-prem installation to have the latest version of Sentry, and the latest SDK (seems you've got that covered).

**Comment by mxmzb** [comment]
@bruno-garcia Oh, I see, thanks for clarifying!

**Comment by lorenzoangelini** [comment]
Hi @HazAT , Into the next release of react-native also in ios hermes will avaiable, react-native-sentry is ready for this?

**Comment by Swatinem** [comment]
If the sourcemaps use a compatible format, its just a matter of tooling to make sure we use it for symbolication. Maybe file a new issue for this?

**Comment by jennmueng** [comment]
Created an Issue to investigate and ensure we support this: https://github.com/getsentry/sentry-react-native/issues/1262
