### ISSUE TITLE
Crash on Android - NoSuchKeyException: frames

### ISSUE THREAD

**Issue by chgsilva** [getsentry/sentry-react-native#742]
OS:
- [ ]  Windows
- [ X]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [ X]  Android

SDK:
- [X ]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`@sentry/react-native`: 1.2.1
`react-native` version: 0.60.5

Init Code:

```
    Sentry.init({
      dsn: "...@sentry.io/...",
      environment: Config.NAME,
      sampleRate: 0.7
    });

    Sentry.setTags({
      appVersion: DeviceInfo.getVersion(),
      systemVersion: DeviceInfo.getSystemVersion()
    });
```

---
I have following issue:

I started to receive this error on both Sentry and Crashlytics, I don't really know how to reproduce it, but it is occurring in +/- 1% of our users and it is really annoying. Seems like to be an issue with Sentry itself.
Anyone know how can i fix it?

```
Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: frames
       at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:124)
       at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:128)
       at com.facebook.react.bridge.ReadableNativeMap.getArray(ReadableNativeMap.java:168)
       at io.sentry.RNSentryModule.sendEvent(RNSentryModule.java:320)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:201)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by olcayjotform** [comment]
We started to receive the same problem with our latest release however we didn't update the sentry library.

@sentry/react-native: 1.0.9
react-native version: 0.59.10


`com.facebook.react.bridge.NoSuchKeyException: frames
    at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:137)
    at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:141)
    at com.facebook.react.bridge.ReadableNativeMap.getArray(ReadableNativeMap.java:202)
    at io.sentry.RNSentryModule.sendEvent(RNSentryModule.java:305)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:227)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
    at java.lang.Thread.run(Thread.java:764)`

**Comment by michael-pr** [comment]
We are also running into this issue, same exact stack trace.
```
"@sentry/react-native": "1.0.6",
"react-native": "0.59.10",
```

**Comment by victormartingarcia** [comment]
Same issue here:

`
"@sentry/react-native": "1.2.1",
"react-native": "0.59.10"
`

**Comment by eeynard** [comment]
Same here:
```
"@sentry/react-native": "^1.2.1",
"react-native": "0.61.5",
```

**Comment by victormartingarcia** [comment]
Patching @sentry/react-native v1.2.1 with the PR #743 fixes the crash. The error shows up on sentry with title `<unlabeled event>` and no stack trace though

**Comment by HazAT** [comment]
`1.2.2` is on the way, which should at least fix the crash.
Also, this PR should fix this issue once and for all https://github.com/getsentry/sentry-react-native/pull/749
Closing this now.

**Comment by vikjovanov** [comment]
Quick question to know if I need to do an emergency patch: Does this result in cutting the application completely? Or is it a background error?

**Comment by samitha9125** [comment]
I can confirm this problem still occurs on some devices. Ex: Samsung Galaxy J7

"@sentry/cli": "1.48.0",
"@sentry/react-native": "1.0.9",
"react-native": "0.61.5"
