### ISSUE TITLE
Unexpected ApplicationNotResponding errors being sent

### ISSUE THREAD

**Issue by jacquesdev** [getsentry/sentry-react-native#786]
OS:
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.2.1
`react-native` version: 0.61.5

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
  Sentry.init({
    dsn: SENTRY_DSN,
    environment: ENV,
  })
```

---
I have the following issue:

I recently upgraded to 1.2.1 of this plugin, and suddenly started to get ApplicationNotResponding errors. According to the java documentation here https://docs.sentry.io/clients/java/integrations/#android, it looks like it's an optional setting that you have to turn on (and that it waits 5 seconds before sending the error).

I have not turned it on, and it seems to complain after 4 seconds.

I realise I don't have the latest version of sentry, and will look at getting that updated soon, but I just wanted to confirm if that was a known issue, and perhaps has been fixed.

If not, can you please confirm why it seems to be enabled by default, since the java docs at least seems to suggest it's an opt in option.

I am using this in my sentry.properties, defaults.url=https://sentry.io/, but assuming that should be as the documentation mentioned.

An example title of the error is `ApplicationNotResponding: Application Not Responding for at least 4000 ms.`

Update:

I decided to use the ANR error by setting the timeout to 15seconds, which is getting ignored, I'm still getting alerts after 4 seconds. I'm going to assume then that explicitly disabling is going to also have no effect.

The biggest problem of all. My quota of events is going to run out in three days, which means sentry becomes useless to me.

**Comment by sudsingh438** [comment]
facing similar issue

**Comment by reyalpsirc** [comment]
Yeah, we also started to see this. In a single day I had like 20 new emails about `ApplicationNotResponding: Application Not Responding for at least 4000 ms.` errors. All with different stacktraces, no breadcrumbs and the user ids are the default ones and not the ones I set on the App during start. Is this normal?

**Comment by brian-perlego** [comment]
Can confirm I have the same issue since an update to `1.3.2`, I receive a lot of error from the same user.

<img width="682" alt="Screenshot 2020-03-10 at 09 05 58" src="https://user-images.githubusercontent.com/47814339/76315098-6bc31500-62ae-11ea-8daf-88eeaf6e10e3.png">

**Comment by jacquesdev** [comment]
@HazAT, could you please investigate. Since it seems I am unable to turn this off (or get it working as expected), at this rate I'll run out of my event quota in three days.

**Comment by marandaneto** [comment]
hey @jacquesdev please look at https://docs.sentry.io/platforms/android/#configuration-options `Application Not Responding (ANR)` section, the link you've shared is of the old Android SDK version.

So to disable it, you need to add in your AndroidManifest file:
`<meta-data android:name="io.sentry.anr.enable" android:value="false" />`

To change the interval, you have to:
`<meta-data android:name="io.sentry.anr.timeout-interval-mills" android:value="15000" />` // if 15 seconds

**Comment by marandaneto** [comment]
could one of you share which device is happening and which Android API level is? or even better, a link to the issue on `sentry.io`
I'm not sure if this is a bug or you are just doing heavy work on the main thread, thanks.

**Comment by brian-perlego** [comment]
Thank you for the AndroidManifest fix, I will try it out.
For me it's happening with `SM-G960F` and `SM-G950F` on Android 9 and 10.

**Comment by jacquesdev** [comment]
@marandaneto, can you please confirm in which version of the react-native plugin this was changed? Ie in which version did it start using the updated sdk where ANR is turned on by default?

**Comment by marandaneto** [comment]
hey @jacquesdev since https://github.com/getsentry/sentry-react-native/releases/tag/1.3.0

**Comment by marandaneto** [comment]
@jacquesdev btw I'd recommend updating the issue description as you stated `SDK version: 1.2.1` and it's for sure >= `1.3.0` thanks

**Comment by marandaneto** [comment]
> Yeah, we also started to see this. In a single day I had like 20 new emails about `ApplicationNotResponding: Application Not Responding for at least 4000 ms.` errors. All with different stacktraces, no breadcrumbs and the user ids are the default ones and not the ones I set on the App during start. Is this normal?

hey, I'd recommend you to open a new issue about the `and the user ids are the default ones and not the ones I set on the App during start`.

**Comment by marandaneto** [comment]
hey, @brian-perlego could you share a link to `sentry.io` or a full stack trace of an unexpected ANR report? I can't really judge if it's a bug on our end or if your App. is just doing heavy work on the main thread.

could any of you create a test repo where you can see if it's actually misfiring ANR reports? I couldn't reproduce by myself, it only fires if it does heavy work on the main thread which then is the right behaviour.

**Comment by jacquesdev** [comment]
@marandaneto. I am using v1.2.1 of this plugin. It looks like that it is potentially using 1.3.1 of the sdk, not sure but can you please confirm?

**Comment by jacquesdev** [comment]
Also @marandaneto - am I right to say this feature is opt-in? I should not be getting it automatically, which is why I believe it is a bug.

**Comment by jacquesdev** [comment]
@marandaneto - here is an id example of my issue:
1566808667

**Comment by marandaneto** [comment]
> Also @marandaneto - am I right to say this feature is opt-in? I should not be getting it automatically, which is why I believe it is a bug.

no, this feature is opt-out as stated on https://docs.sentry.io/platforms/android/#configuration-options
pay attention at: `If you do not want to monitor the ANR, please add the following line into your manifest.`

```
<application>
    <meta-data android:name="io.sentry.anr.enable" android:value="false" />
</application>
```

**Comment by marandaneto** [comment]
> @marandaneto. I am using v1.2.1 of this plugin. It looks like that it is potentially using 1.3.1 of the sdk, not sure but can you please confirm? #796 confirms its 1.2.1, so not an issue with my bug report.

I think there's a problem in your build script or something, `sentry-react-native` only starts using `sentry-android-2.0.0` >= 1.3.0 so it can't be `1.2.1`, please double-check it, maybe clean it up and use the wizard again?

**Comment by marandaneto** [comment]
> @marandaneto - here is an id example of my issue:
> 1566808667

what's the `org`?

**Comment by jacquesdev** [comment]
@marandaneto - org is `olio`

**Comment by marandaneto** [comment]
@jacquesdev thanks, what's about the SDK version? have you double-checked it?

<img width="914" alt="Screenshot 2020-03-17 at 09 01 06" src="https://user-images.githubusercontent.com/5731772/76834704-e8fe0500-682d-11ea-8a4a-dc9d159074bb.png">

this is a SS from an issue of yours, so if you still see in your code 1.2.1, I'd suggest to clean it up and set it up again.

**Comment by jacquesdev** [comment]
Thanks @marandaneto, it seems the version we were using in our package lock file was not the same one as specificied in our package.json. We have now fixed

**Comment by 39otrebla** [comment]
Still happening to us on SDK version `2.0.2`. Getting thousands of events, pretty sure none of them is an actual ANR.

**Comment by marandaneto** [comment]
@39otrebla `@sentry/react-native@1.6.2` should be using the Android SDK `v2.2.0` and not `v2.0.2`, if you downgrade it manually, undo it.

if it didn't upgrade automatically when you upgraded the `@sentry/react-native@1.6.2`, please raise a new issue, also run the wizard again, this issue is resolved but it seems you are using an older version of the Android SDK.
